# Generated by Django 4.1.3 on 2023-07-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_alter_productcategory_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='url_title',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='عنوان در url'),
        ),
    ]
