# Generated by Django 4.1.3 on 2022-12-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='fullـname',
            new_name='full_name',
        ),
    ]
