# Generated by Django 4.1.3 on 2023-04-04 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles_module', '0002_alter_articlecategory_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles_module.articlecategory', verbose_name='دسته بندی والد'),
        ),
    ]
