# Generated by Django 4.1.3 on 2023-03-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='git_hub_url',
            field=models.URLField(max_length=250, null=True, verbose_name='آدرس گیت هاب'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(max_length=250, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.CharField(max_length=250, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='fax',
            field=models.CharField(max_length=250, null=True, verbose_name='فکس'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(max_length=250, null=True, verbose_name='شماره تلفن'),
        ),
    ]
