# Generated by Django 4.1.3 on 2023-04-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings_module', '0003_footerlinksbox_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات اسلایدر')),
                ('url', models.URLField(max_length=250, verbose_name='لینک')),
                ('url_title', models.CharField(max_length=150, verbose_name='َعنوان لینک')),
                ('image', models.ImageField(upload_to='images/slider/', verbose_name='تصویر اسلایدر')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر ها',
            },
        ),
    ]
